# [default: None] A domain name to append to challenge names to create their default common name
domain: naum.tamuctf.com

# [default: './challenges'] The directory which contains your challenges
# If the the path is relative, it will be relative to the generated docker-compose.yml file
challenges_directory: ./challenges

# [required] Configurations for each challenge
challenges:
    helpful-builder:
        port: 2001
        files:
            - helpful-builder/docker-compose.yml
        commonname: 10.0.2.9
        ifconfig_push: 172.30.0.14/28
