baseURL = ""
languageCode = "en-US"
title = "My first blog!"
theme = "easybook"

pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

paginate = 3
[[menu.main]]
  name = "Home"
  weight = 10
  url = "/"

# site info
[params]
  author = "lucia.turner"
  whoami = ""
  avatar = "/images/avatar.jpg"
  keywords = [""]
  description = ""

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []
  customJS = []