[package]
name = "lejit"
version = "0.1.0"
authors = ["Addison Crump <addisoncrump@tamu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dynasm = "0.5.2"
dynasmrt = "0.5.2"
itertools = "0.8.2"
libc = "0.2.66"
